<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page import="java.util.*" %>
<%@ page import="quicksplit.core.*" %>

<html>

	<head>
	  <title>QuickSplit: Add Results</title>
	  <jsp:include page="common/includes.jsp" />
	  
	  <script type="text/javascript">
    
	    $(function(){
	    	
	    	// configure date field
				$("#datepicker").datepicker({
					dateFormat: "dd/mm/yy",
					defaultDate: new Date()
				});
				
			  // capture field values from request params
			  var results = [];
			  <c:forEach varStatus="loop" items="${paramValues.Player}">
			  	results.push({
			  		player: "${paramValues.Player[loop.index]}",
			  		amount: "${paramValues.Result[loop.index]}" });
			  </c:forEach>
			  
			  generateFields( results );
		  });
	    
	    function resetHandlers()
	    {
				$( "input[type='text'][name='Player']" ).autocomplete({
				  source: players,
					delay: 0
				});
				
				$( "input[type='text']" ).blur( function( e ){
					addEmptyRow();
			  });
	    }
		  
		  function clearForm()
		  {
		    $( "input[type='text']" ).val( "" );
		  }
		  
		  function generateFields( results )
		  {
			  for( var i=0; i<results.length; i++ )
				{
				  $( "#resultsTable tbody" ).append( getRowElement( results[i].player, results[i].amount ) );
				}
			  addEmptyRow();
			  resetHandlers();
		  }
		  
		  // adds an empty result row provided the final row isn't already empty
		  function addEmptyRow()
		  {
			  if( $( "#resultsTable tbody tr:last input:first" ).val() != "" ||
					  $( "#resultsTable tbody tr:last input:last" ).val() != "" )
				{
			  	$( "#resultsTable tbody" ).append( getRowElement( "", "" ) );
			  	resetHandlers();
				}
		  }
		  
		  function getRowElement( player, result )
		  {
			  return $( 
					  "<tr>" + 
					    "<td><input type='text' name='Player' value='" + player + "'/></td>" + 
					    "<td><input type='text' name='Result' value='" + result + "'/></td>" + 
					  "</tr>" );
		  }
	  </script>
	</head>
	
	<body>
		<h1>Add Results</h1>
		
		<c:if test="${not empty Errors}">
	    <div class="ui-widget">
				<div style="padding: 0pt 0.7em; margin-top: 20px;" class="ui-state-error ui-corner-all">
				  <c:forEach items="${Errors}" var="error">
						<p>
							<span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert">&nbsp;</span>
							${error}
						</p>
				  </c:forEach>
				</div>
			</div>
	  </c:if>

		<c:if test="${not empty Warnings}">
	    <div class="ui-widget">
				<div style="padding: 0pt 0.7em; margin-top: 20px;" class="ui-state-highlight ui-corner-all"> 
					<c:forEach items="${Warnings}" var="warning">
					  <p>
					  	<span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info">&nbsp;</span>
						  ${warning}
						</p>
				  </c:forEach>
				</div>
			</div>
		</c:if>
		
		<c:if test="${Success}">
	    <div class="ui-widget">
				<div style="padding: 0pt 0.7em; margin-top: 20px;" class="ui-state-success ui-corner-all"> 
				  <p>
				  	<span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-check">&nbsp;</span>
					  New record has been added for ${NewGame}.
					</p>
				</div>
			</div>
		</c:if>
		
		
		<br/>
		<form name="AddResultForm" method="get" action="AddResultAction">
		
			<!-- Datepicker -->
			<label>Game Date:</label>
			<input type="text" id="datepicker" name="Date" size="15" value="${param.Date}" />
			<br/>
			
			<label>Game Type:</label> 
			<select name="GameType">
				<c:forEach items="${GameTypes}" var="type">
					<c:choose>
						<c:when test="${type==param.GameType}">
					    <option selected="selected">${type}</option>
						</c:when>
						<c:otherwise>
						  <option>${type}</option>
						</c:otherwise>
				  </c:choose>
				</c:forEach>
			</select>
			<br/><br/>
			
			<table id="resultsTable">
				<thead>
					<tr>
						<th>Player</th>
						<th>$</th>
				  </tr>
				</thead>
				
				<!-- Table content dynamically generated by javascript -->
				<tbody>
				</tbody>
				
			</table>
			
			<br/><br/>
			<input type="submit" name="submit" value="Submit" />
			<input type="button" value="Clear" onclick="javascript:clearForm();" />
			<c:if test="${Confirm}">
			  <input type="submit" name="submit" value="Confirm" />
			</c:if>
		</form>
		
  </body>
  
</html>